-- Total revenue
SELECT 
    SUM(Booking_Value) AS Revenue
FROM
    bookings
WHERE
    Booking_Status = 'Success';

-- category wise booking status
SELECT 
    Booking_Status, COUNT(*) AS count_of_status,ROUND((COUNT(*) * 100.0 / (SELECT COUNT(*) FROM bookings)), 2) AS percentage
FROM
    bookings
GROUP BY Booking_Status;

-- How many unique users booked a ride?

SELECT 
    COUNT(Customer_ID) - COUNT(DISTINCT Customer_ID) AS Unique_users
FROM
    bookings;

-- What are the top 20 most frequently used pickup locations?
SELECT 
    Pickup_Location, COUNT(*) AS frequent_pickup_location
FROM
    bookings
GROUP BY Pickup_Location
ORDER BY frequent_pickup_location DESC
LIMIT 20;

-- What is the average fare by vehical type

SELECT 
    Vehicle_Type, ROUND(AVG(Booking_Value), 1) AS avg_fare
FROM
    bookings
GROUP BY Vehicle_Type  ;            

-- Which ride category (Micro, Mini, Prime, etc.) is most popular
SELECT 
    Vehicle_Type, COUNT(*) AS Count
FROM
    bookings
GROUP BY Vehicle_Type;                                                   

-- What is the average distance traveled in each category?
SELECT 
    Vehicle_Type, ROUND(AVG(Ride_Distance), 1) AS avg_dist
FROM
    bookings
GROUP BY Vehicle_Type;      

-- "What is the total revenue generated by each vehicle type from only successful rides?"
SELECT 
    Vehicle_Type, SUM(Booking_Value) AS revenue
FROM
    bookings
WHERE
    Booking_Status = 'Success'
GROUP BY Vehicle_Type
ORDER BY revenue DESC;           

-- Weekly revenue
SELECT 
    EXTRACT(WEEK FROM Date) AS Weeks,
    SUM(Booking_Value) AS weekly_revenue
FROM
    bookings
WHERE
    Booking_Status = 'Success'
GROUP BY Weeks
ORDER BY weekly_revenue DESC;

-- During which hours of the day is ride demand the highest? 
select 
case
	when hour(Time) between 6 and 11 then 'morning'
    when hour(Time) between 12 and 16 then 'afternoon'
    when hour(Time) between 17 and 20 then  'noon'
    else 'night'
end as period , count(*) as no_of_booking from bookings group by period order by no_of_booking desc;

-- How many bookings were canceled by customer, and what were the key reasons behind them?
SELECT 
    Booking_ID, Canceled_Rides_by_Customer
FROM
    bookings
WHERE
    Canceled_Rides_by_Customer IS NOT NULL;

-- count of rides cancle by customer
SELECT 
    Canceled_Rides_by_Customer, COUNT(*) AS counts
FROM
    bookings
WHERE
    Canceled_Rides_by_Customer IS NOT NULL
GROUP BY Canceled_Rides_by_Customer;

-- How many bookings were canceled by Driver, and what were the key reasons behind them?
SELECT 
    Booking_ID, Canceled_Rides_by_Driver
FROM
    bookings
WHERE
    Canceled_Rides_by_Driver IS NOT NULL;

-- count of rides cancle by customer
SELECT 
    Canceled_Rides_by_Driver, COUNT(*) AS counts
FROM
    bookings
WHERE
    Canceled_Rides_by_Driver IS NOT NULL
GROUP BY Canceled_Rides_by_Driver;

-- Are there specific routes (pickup to drop) that consistently generate higher revenues sql query
SELECT
	Pickup_Location,
    Drop_Location,
	ROUND(AVG(Ride_Distance), 2) AS avg_ride_distance,
    COUNT(*) AS count_of_ride,
    SUM(Booking_Value) AS total_revenue,
    ROUND(AVG(Booking_Value), 2) AS avg_revenue_per_ride
FROM
    bookings
WHERE
    Booking_Status = 'Success'
GROUP BY Pickup_Location , Drop_Location
HAVING total_revenue > 0
ORDER BY total_revenue DESC
LIMIT 10;
                                                                                                                                                                                                               ;